#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/jpa_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&verifyServerCertificate=false
#        driver-class-username: com.mysql.jdbc.Driver
#        username: root
#        password: 980720
#  jpa:
#        hibernate:
#          ddl-auto: update
#        show-sql: true
##  jackson.serialization.indent_output: true
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/jpa_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&verifyServerCertificate=false
      driver-class-username: com.mysql.jdbc.Driver
      username: root
      password: 980720
   jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
   redis:
       host: 127.0.0.1
       port: 6379
server:
  port: 8081
#  配置日志打印的等级
logging:
    level:
      com.example.demo: DEBUG